name: python-workflow
on: [workflow_dispatch, push]

jobs:
  lint_flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        python3 -m flake8 main.py
        python3 -m flake8 sum.py

  lint_black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Lint with Black
      uses: rickstaa/action-black@v1.3.0
      with:
        black_args: ". --check --verbose"

  test:
    runs-on: ubuntu-latest
    needs: [lint_flake8, lint_black]
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with Pytest
      run: python3 -m pytest sum.py --doctest-modules
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: curl google.com
      run: curl https://www.google.com/